name: "publish"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: install frontend dependencies
        run: npm ci

      - name: Install OpenSSL
        if: matrix.platform == 'windows-latest'
        run: choco install openssl

      - name: Set OPENSSL_DIR
        if: matrix.platform == 'windows-latest'
        run: |
          $opensslDir = (Get-Command openssl).Source | Split-Path -Parent
          echo "OPENSSL_DIR=$opensslDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: "dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5MUUvOHJTUWZjTzRFYTEvQ1A4M1RjemZhMkJwVWNjL2ZBMXRTb1VXSnBaWUFBQkFBQUFBQUFBQUFBQUlBQUFBQVp1akFZd0hoR2oxcXNDZGI0U2o4aEx1NFNZNzdxLy9EZllURThPcXJHaFZsdHVvU0ZXd3Y5OUt2R3B0V3VVZzZTSnBqVFg2b09IWndvRk1pSzBqTnpmQno4QXVEL1FNaXBEWnRucjZERUhiTVR3OEhHV0dpK2dBSFBTT0lBMUxGTFZ3ZWtwbFBGMEE9Cg=="
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: "    "
        with:
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}

  clone-release:
    # needs: publish-tauri
    runs-on: "ubuntu-22.04"
    steps:
      - name: Duplicate Release With Asset to public_Repo
        id: Release-AIO
        uses: Hs1r1us/Release-AIO@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "inherit"
          body: "hello world"
          repo: "MrChaker/upcount-updater"
